CREATE TABLE "USER_DEV"."PRODUTO_EXERCICIO" (
    "COD" VARCHAR2(5 BYTE), 
    "DESCRICAO" VARCHAR2(100 BYTE), 
    "CATEGORIA" VARCHAR2(100 BYTE)
);

CREATE UNIQUE INDEX "USER_DEV"."PRODUTO_EXERCICIO_COD_PK" ON "USER_DEV"."PRODUTO_EXERCICIO" ("COD") ;

ALTER TABLE "USER_DEV"."PRODUTO_EXERCICIO" ADD CONSTRAINT "PRODUTO_EXERCICIO_COD_PK" PRIMARY KEY ("COD");

CREATE TABLE "USER_DEV"."PRODUTO_VENDA_EXERCICIO" 
   (    "ID" NUMBER(5,0), 
    "COD_PRODUTO" VARCHAR2(5 BYTE), 
    "DATA" DATE, 
    "QUANTIDADE" FLOAT(126), 
    "PRECO" FLOAT(126), 
    "VALOR_TOTAL" FLOAT(126), 
    "PERCENTUAL_IMPOSTO" FLOAT(126)
   );

CREATE UNIQUE INDEX "USER_DEV"."PRODUTO_VENDA_EXERCICIO_ID_PK" ON "USER_DEV"."PRODUTO_VENDA_EXERCICIO" ("ID") ;

ALTER TABLE "USER_DEV"."PRODUTO_VENDA_EXERCICIO" ADD CONSTRAINT "PRODUTO_VENDA_EXERCICIO_ID_PK" PRIMARY KEY ("ID");

ALTER TABLE "USER_DEV"."PRODUTO_VENDA_EXERCICIO" ADD CONSTRAINT "PRODUTO_VENDA_EXERCICIO_PRODUTO_EXERCICIO_COD" FOREIGN KEY ("COD_PRODUTO") 
    REFERENCES "USER_DEV"."PRODUTO_EXERCICIO" ("COD");

Insert into PRODUTO_EXERCICIO (COD,DESCRICAO,CATEGORIA) values ('41232','Sabor de Verão > Laranja > 1 Litro','Sucos de Frutas');
Insert into PRODUTO_EXERCICIO (COD,DESCRICAO,CATEGORIA) values ('32223','Sabor de Verão > Uva > 1 Litro','Sucos de Frutas');
Insert into PRODUTO_EXERCICIO (COD,DESCRICAO,CATEGORIA) values ('67120','Frescor da Montanha > Aroma Limão > 1 Litro','Águas');
Insert into PRODUTO_EXERCICIO (COD,DESCRICAO,CATEGORIA) values ('92347','Aroma do Campo > Mate > 1 Litro','Mate');
Insert into PRODUTO_EXERCICIO (COD,DESCRICAO,CATEGORIA) values ('33854','Frescor da Montanha > Aroma Laranja > 1 Litro','Águas');

Insert into PRODUTO_VENDA_EXERCICIO (ID,COD_PRODUTO,DATA,QUANTIDADE,PRECO,VALOR_TOTAL,PERCENTUAL_IMPOSTO) values ('1','41232',to_date('01/01/22','DD/MM/RR'),'100','10','1000','10');
Insert into PRODUTO_VENDA_EXERCICIO (ID,COD_PRODUTO,DATA,QUANTIDADE,PRECO,VALOR_TOTAL,PERCENTUAL_IMPOSTO) values ('2','92347',to_date('01/01/22','DD/MM/RR'),'200','25','5000','15');
Insert into PRODUTO_VENDA_EXERCICIO (ID,COD_PRODUTO,DATA,QUANTIDADE,PRECO,VALOR_TOTAL,PERCENTUAL_IMPOSTO) values ('3','41232',to_date('01/02/22','DD/MM/RR'),'250','20','5000','10');
Insert into PRODUTO_VENDA_EXERCICIO (ID,COD_PRODUTO,DATA,QUANTIDADE,PRECO,VALOR_TOTAL,PERCENTUAL_IMPOSTO) values ('4','32223',to_date('03/02/22','DD/MM/RR'),'200','16','3200','10');
Insert into PRODUTO_VENDA_EXERCICIO (ID,COD_PRODUTO,DATA,QUANTIDADE,PRECO,VALOR_TOTAL,PERCENTUAL_IMPOSTO) values ('5','92347',to_date('05/02/22','DD/MM/RR'),'200','16','3200','15');
Insert into PRODUTO_VENDA_EXERCICIO (ID,COD_PRODUTO,DATA,QUANTIDADE,PRECO,VALOR_TOTAL,PERCENTUAL_IMPOSTO) values ('6','41232',to_date('02/03/22','DD/MM/RR'),'210','19','3990','10');
Insert into PRODUTO_VENDA_EXERCICIO (ID,COD_PRODUTO,DATA,QUANTIDADE,PRECO,VALOR_TOTAL,PERCENTUAL_IMPOSTO) values ('7','33854',to_date('05/03/22','DD/MM/RR'),'180','21','3780','20');
Insert into PRODUTO_VENDA_EXERCICIO (ID,COD_PRODUTO,DATA,QUANTIDADE,PRECO,VALOR_TOTAL,PERCENTUAL_IMPOSTO) values ('8','92347',to_date('09/03/22','DD/MM/RR'),'170','20','3400','15');