-- dando privilégios ao user_app

GRANT EXECUTE ON ATUALIZAR_CLI_SEG_MERCADO TO user_app;
GRANT EXECUTE ON ATUALIZAR_FATURAMENTO_PREVISTO TO user_app;
GRANT EXECUTE ON EXCLUIR_CLIENTE TO user_app;
GRANT EXECUTE ON INCLUIR_CLIENTE TO user_app;
GRANT EXECUTE ON INCLUINDO_PRODUTO TO user_app;
GRANT EXECUTE ON INCLUINDO_DADOS_VENDA TO user_app;

GRANT SELECT ON CLIENTE TO user_app;
GRANT SELECT ON PRODUTO_EXERCICIO TO user_app;
GRANT SELECT ON PRODUTO_VENDA_EXERCICIO TO user_app;

-- sinonimos:
CREATE PUBLIC SYNONYM INCLUIR_CLIENTE FOR USER_DEV.INCLUIR_CLIENTE;
CREATE PUBLIC SYNONYM ATUALIZAR_CLI_SEG_MERCADO FOR USER_DEV.ATUALIZAR_CLI_SEG_MERCADO;
CREATE PUBLIC SYNONYM ATUALIZAR_FATURAMENTO_PREVISTO FOR USER_DEV.ATUALIZAR_FATURAMENTO_PREVISTO;
CREATE PUBLIC SYNONYM EXCLUIR_CLIENTE FOR USER_DEV.EXCLUIR_CLIENTE;
CREATE PUBLIC SYNONYM INCLUINDO_PRODUTO FOR USER_DEV.INCLUINDO_PRODUTO;
CREATE PUBLIC SYNONYM INCLUINDO_DADOS_VENDA FOR USER_DEV.INCLUINDO_DADOS_VENDA;

CREATE PUBLIC SYNONYM CLIENTE FOR USER_DEV.CLIENTE;
CREATE PUBLIC SYNONYM PRODUTO_EXERCICIO FOR USER_DEV.PRODUTO_EXERCICIO;
CREATE PUBLIC SYNONYM PRODUTO_VENDA_EXERCICIO FOR USER_DEV.PRODUTO_VENDA_EXERCICIO;


