SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') AS nome_usuario
FROM DUAL;

SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') AS nome_conexao
FROM DUAL;

SELECT SYS_CONTEXT('USERENV', 'DB_UNIQUE_NAME') AS nome_servico
FROM DUAL;

SELECT DISTINCT PORT FROM V$SESSION
WHERE SID = SYS_CONTEXT('USERENV', 'SID');

SELECT UTL_INADDR.GET_HOST_NAME() AS host FROM DUAL;


