-- acessando o pacote pelo user_app

EXECUTE CLIENTE_PAC.INCLUIR_CLIENTE(11, 'SEGUNDO CLIENTE INCLUIDO POR USER_APP VIA PACKAGE', '455564', 2, 12000)

EXECUTE CLIENTE_PAC.EXCLUIR_CLIENTE(11);

SELECT * FROM CLIENTE;